apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.db.env.POSTGRES_USER | b64enc | quote }}
  password: {{ .Values.db.env.POSTGRES_PASSWORD | b64enc | quote }}