# =============================================================================
# advanced/secrets/stack-with-secrets.yml
# =============================================================================
# Demonstrates Docker Swarm secrets in a stack file.
# Secrets must be created BEFORE deploying this stack:
#
#   echo "postgres_password" | docker secret create db_password -
#   echo "redis_password"    | docker secret create redis_password -
#   echo "jwt_secret_key"    | docker secret create jwt_secret -
#
# Deploy: docker stack deploy -c stack-with-secrets.yml secureapp
# =============================================================================

version: "3.9"

networks:
  app-net:
    driver: overlay
    driver_opts:
      encrypted: "true"

# ── Secrets declaration ───────────────────────────────────────────────────────
# All secrets used by this stack must be declared here.
# external: true means they already exist in the swarm (created separately).
secrets:
  db_password:
    external: true    # pre-created with `docker secret create`
  redis_password:
    external: true
  jwt_secret:
    external: true

  # Alternatively, create inline (less secure — value in compose file):
  # api_key:
  #   name: api_key_v1
  #   file: ./secrets/api_key.txt   # read from a local file at deploy time

services:
  # ── PostgreSQL with secrets ────────────────────────────────────────────────
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      # Reference secret file path instead of hardcoding the value
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password     # mounted at /run/secrets/db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "appuser", "-d", "appdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ── Redis with secrets ────────────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    command: >
      sh -c "redis-server --requirepass $$(cat /run/secrets/redis_password)"
    secrets:
      - redis_password
    networks:
      - app-net
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M

  # ── API reading secrets from /run/secrets/ ────────────────────────────────
  api:
    image: node:20-alpine
    command: >
      sh -c "
        export DB_PASSWORD=$$(cat /run/secrets/db_password)
        export REDIS_PASSWORD=$$(cat /run/secrets/redis_password)
        export JWT_SECRET=$$(cat /run/secrets/jwt_secret)
        node server.js
      "
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: appdb
      DB_USER: appuser
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    secrets:
      # Mount with custom target path and permissions
      - source: db_password
        target: /run/secrets/db_password
        mode: 0400        # read-only, owner only
      - source: redis_password
        target: /run/secrets/redis_password
        mode: 0400
      - source: jwt_secret
        target: /run/secrets/jwt_secret
        mode: 0400
    networks:
      - app-net
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

volumes:
  postgres_data:
    driver: local