# =============================================================================
# docker-swarm/example/docker-stack.yml
# =============================================================================
# Full production-grade stack:
#   Traefik    — reverse proxy + automatic TLS (replaces nginx)
#   Node.js    — REST API (3 replicas, rolling update)
#   PostgreSQL — persistent database with Swarm secrets
#   Redis      — session cache
#
# Prerequisites:
#   docker swarm init
#   echo "dbpassword"    | docker secret create db_password -
#   echo "redispassword" | docker secret create redis_password -
#
# Deploy: docker stack deploy -c docker-stack.yml taskapp
# Logs:   docker service logs taskapp_api -f
# Scale:  docker service scale taskapp_api=5
# Remove: docker stack rm taskapp
# =============================================================================

version: "3.9"

# ── Networks ──────────────────────────────────────────────────────────────────
networks:
  traefik-public:
    driver: overlay
    attachable: true
  backend:
    driver: overlay
    driver_opts:
      encrypted: "true"   # encrypt backend traffic

# ── Volumes ──────────────────────────────────────────────────────────────────
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  traefik_certs:
    driver: local

# ── Secrets ──────────────────────────────────────────────────────────────────
secrets:
  db_password:
    external: true
  redis_password:
    external: true

services:
  # ── Traefik: reverse proxy + automatic TLS ─────────────────────────────────
  traefik:
    image: traefik:v3.0
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=admin@example.com
      - --certificatesresolvers.letsencrypt.acme.storage=/certs/acme.json
      # Redirect all HTTP to HTTPS
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
    ports:
      - target: 80
        published: 80
        mode: host    # host mode: bind directly to node IP (better performance)
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro   # read-only docker socket
      - traefik_certs:/certs
    networks:
      - traefik-public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager    # Traefik reads Docker API — must run on manager
      labels:
        traefik.enable: "true"
        traefik.http.routers.dashboard.rule: "Host(`traefik.example.com`)"
        traefik.http.routers.dashboard.service: api@internal
        traefik.http.routers.dashboard.tls.certresolver: letsencrypt
        traefik.http.routers.dashboard.middlewares: auth
        traefik.http.middlewares.auth.basicauth.users: "admin:$$apr1$$..."
        traefik.http.services.traefik.loadbalancer.server.port: "8080"
      restart_policy:
        condition: on-failure
        delay: 5s

  # ── PostgreSQL ────────────────────────────────────────────────────────────
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: taskapp
      POSTGRES_USER: taskapp
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.storage == ssd    # prefer SSD nodes for database
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "taskapp", "-d", "taskapp"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ── Redis ─────────────────────────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    command: >
      sh -c "redis-server --requirepass $$(cat /run/secrets/redis_password) --appendonly yes"
    secrets:
      - redis_password
    volumes:
      - redis_data:/data
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # ── Node.js API ───────────────────────────────────────────────────────────
  api:
    image: taskapp-api:1.0.0
    environment:
      NODE_ENV: production
      PORT: "3000"
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: taskapp
      DB_USER: taskapp
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    secrets:
      - source: db_password
        target: /run/secrets/db_password
        mode: 0400
      - source: redis_password
        target: /run/secrets/redis_password
        mode: 0400
    networks:
      - traefik-public
      - backend
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 15s
        order: start-first
        failure_action: rollback
        monitor: 30s
        max_failure_ratio: 0.1
      rollback_config:
        parallelism: 2
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M
      labels:
        traefik.enable: "true"
        traefik.http.routers.api.rule: "Host(`api.example.com`)"
        traefik.http.routers.api.tls.certresolver: letsencrypt
        traefik.http.services.api.loadbalancer.server.port: "3000"
        traefik.http.services.api.loadbalancer.healthcheck.path: /health
        traefik.http.services.api.loadbalancer.healthcheck.interval: 10s
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s